export const designTokenConfig = {
  color: {
    canvas: '#EEF2FF',
    surface: '#FFFFFF',
    surfaceElevated: '#F7FAFF',
    textPrimary: '#0F1A2F',
    textSecondary: '#42506B',
    textMuted: '#66748F',
    textOnAccent: '#FFFFFF',
    accent: '#1E5BFF',
    accentStrong: '#0C43D1',
    accentSoft: '#DBE6FF',
    success: '#1F9D66',
    warning: '#FF9F1C',
    danger: '#D94B4B',
    border: '#D5DEEF',
    divider: '#E7ECF7',
    overlay: 'rgba(15, 26, 47, 0.42)',
    decorativeA: '#DCE8FF',
    decorativeB: '#CFE0FF',
  },
  spacing: {
    xxs: 4,
    xs: 8,
    sm: 12,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 40,
  },
  radius: {
    sm: 8,
    md: 12,
    lg: 16,
    xl: 22,
    pill: 999,
  },
  typography: {
    size: {
      caption: 12,
      bodySm: 13,
      body: 15,
      subtitle: 18,
      title: 26,
      hero: 30,
    },
    lineHeight: {
      caption: 16,
      bodySm: 18,
      body: 22,
      subtitle: 24,
      title: 32,
      hero: 36,
    },
    weight: {
      regular: '400',
      medium: '500',
      semibold: '600',
      bold: '700',
    },
  },
  shadow: {
    card: {
      shadowColor: '#10254A',
      shadowOpacity: 0.08,
      shadowRadius: 14,
      shadowOffset: { width: 0, height: 8 },
      elevation: 4,
    },
    raised: {
      shadowColor: '#10254A',
      shadowOpacity: 0.14,
      shadowRadius: 22,
      shadowOffset: { width: 0, height: 14 },
      elevation: 8,
    },
  },
  motion: {
    fast: 120,
    normal: 220,
    slow: 340,
  },
} as const;
